name: logsink
synopsis: A logging framework for Haskell
category: System
description: |
  @logsink@ is a logging framework for Haskell.  It is meant to be used in
  conjunction with @logging-facade@ (<http://hackage.haskell.org/package/logging-facade>).

  For more information and usage, consult the README: <https://github.com/sol/logsink#readme>
copyright: (c) Zalora South East Asia Pte. Ltd
license: MIT
maintainer: Simon Hengel <sol@typeful.net>

github: sol/logsink

ghc-options: -Wall

dependencies:
  - base == 4.*
  - logging-facade
  - hsyslog >= 5
  - time

source-dirs:
  - src

library:
  exposed-modules:
    - System.Logging.LogSink.Config
    - System.Logging.LogSink.Core
    - System.Logging.LogSink.Format

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies: hspec == 2.*
